In [3]:
import os
import pandas as pd

root_dir = os.path.join(r'C:\Users\singku\google drive ku 175T\_G-Project\datasets\CPN_all\CPN_utf8.csv')
df = pd.read_csv(root_dir, encoding='utf-8', index_col=0)

In [18]:
df['ID'].str.split('_').to_frame(name='tmp')
df = df.rename(columns={'ID' : 'file_name'})
df

          file_name  width  height       roi
0       FH_I0000677    436     513  0.052833
1     FH_I0000916_1    437     486  0.012775
2     FH_I0000916_2    436     523  0.016560
3     FH_I0000922_1    607     415  0.018491
4       FH_I0001111    771     568  0.014956
..              ...    ...     ...       ...
485  POP_I0025306_2    416     567  0.011509
486  POP_I0025738_1    451     311  0.014216
487  POP_I0025740_1    450     313  0.018069
488    POP_I0030243    769     548  0.010044
489    POP_I0030249    761     528  0.008350

[490 rows x 4 columns]

In [21]:
tmp = pd.DataFrame(df['file_name'].str.split('_').to_list(), columns=['region', 'ID', 'subset']).fillna(1)
tmp = pd.concat([tmp, df], axis=1)
tmp.to_csv(root_dir, encoding='utf-8')